server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: edbd66449841f86b9a850c7ab15e881a
            client-secret: u8ieBRWV9DprGwlmyYuM2kB5rTOPNIdz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sbb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 12345678

  mail:
    host: smtp.naver.com
    port: 465
    username: "0101angela@naver.com"
    password: "home1726^^"
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
          trust: smtp.naver.com

